[[redirects]]
  from = "/r"
  to = "https://www.reddit.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/subreddits"
  to = "https://www.reddit.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "https://sentry.io/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

# Skip all post processing in deploy previews,
# ignoring any other settings
[context.deploy-preview.processing]
  skip_processing = true

[context.branch-name.processing]
  skip_processing = false
[context.branch-name.processing.images]
  compress = false
[[redirects]]
from="/call-proxy/*"
to="/.netlify/functions/call-proxy/:splat"
status=301
